### ISSUE TITLE
All executable scripts should have a proper shebang

### ISSUE THREAD

**Issue by hans-d** [cloudposse/geodesic#889] opened 2023-11-23 18:22 UTC
## Describe the Bug

Various executable files (scripts) are lacking a proper shebang.

## Additional Context

When using this container as a base for a devcontainer, and tooling wants to execute things with `sh`, profile scripts are failing as the scripts in many cases require bash

**Comment by Nuru** [comment] 2023-12-02 11:10
@hans-d Many scripts in Geodesic (most commonly scripts under `etc/profile.d` or ending in `.sh`) are not intended to be run as scripts but are rather intended to be sourced, which is why they do not have a shebang.

If there are other scripts, such as under `usr/local/bin`, that are intended to be run as command scripts and are missing shebangs, please list them specifically and we will look into it.

If you are running into other failures, please let us know which version and which base OS (Debian or Alpine) you are using along with a description of the failure that would enable us to reproduce it.

**Comment by Nuru** [comment] 2024-01-12 03:22
I am closing this because of a lack of information, without which this looks like "not a bug". This issue may be reopened if additional information is provided which demonstrates a problem in need of a solution.

**Closed by Nuru** 2024-01-12 03:22 UTC
Labels: bug, needs more information
